package project

import (
	"context"
	"os"
	"path/filepath"
	"testing"

	"github.com/ratibordas/go-mcp-codeweft/internal/config"
)

func TestDiscoverFiltersUnsafeAndUnsupportedFiles(t *testing.T) {
	root := t.TempDir()
	writeFile(t, root, "src/main.go", "package src\n")
	writeFile(t, root, "src/generated.go", "// Code generated by x DO NOT EDIT.\npackage src\n")
	writeFile(t, root, "src/binary.go", "package src\x00")
	writeFile(t, root, ".env", "TOKEN=secret\n")
	writeFile(t, root, "keys/id_rsa", "secret\n")
	writeFile(t, root, "assets/image.png", "png\x00")
	writeFile(t, root, "notes.bin", "bin\x00")
	writeFile(t, root, "src/main_test.go", "package src\n")
	writeFile(t, root, "skip/hidden.go", "package skip\n")

	files, err := DiscoverWithIndex(context.Background(), root, config.Index{ExcludeDirNames: []string{"skip"}})
	if err != nil {
		t.Fatal(err)
	}
	if len(files) != 1 || files[0].Path != "src/main.go" || files[0].Language != "go" {
		t.Fatalf("unexpected files: %+v", files)
	}
}

func TestDiscoverAcceptsGitTrackedAndUntrackedButNotIgnored(t *testing.T) {
	root := t.TempDir()
	git(t, root, "init")
	git(t, root, "config", "user.email", "test@example.com")
	git(t, root, "config", "user.name", "Test")
	writeFile(t, root, ".gitignore", "ignored.go\n")
	writeFile(t, root, "tracked.go", "package tracked\n")
	git(t, root, "add", "tracked.go", ".gitignore")
	git(t, root, "commit", "-m", "initial")
	writeFile(t, root, "untracked.ts", "export const x = 1\n")
	writeFile(t, root, "ignored.go", "package ignored\n")

	files, err := Discover(context.Background(), root)
	if err != nil {
		t.Fatal(err)
	}
	if paths := filePaths(files); len(paths) != 2 || paths[0] != "tracked.go" || paths[1] != "untracked.ts" {
		t.Fatalf("unexpected paths: %q", paths)
	}
}

func TestResolveInsideRootRejectsEscapingSymlink(t *testing.T) {
	root := t.TempDir()
	outside := t.TempDir()
	if err := os.Symlink(outside, filepath.Join(root, "escape")); err != nil {
		t.Fatal(err)
	}
	if _, err := resolveInsideRoot(root, "escape/secret.md"); err == nil {
		t.Fatal("expected symlink escape to fail")
	}
}

func TestDiscoverSupportsCommonJSAndESModules(t *testing.T) {
	root := t.TempDir()
	writeFile(t, root, "module.mjs", "export const m = 1\n")
	writeFile(t, root, "common.cjs", "module.exports = 1\n")

	files, err := Discover(context.Background(), root)
	if err != nil {
		t.Fatal(err)
	}
	if paths := filePaths(files); len(paths) != 2 || paths[0] != "common.cjs" || paths[1] != "module.mjs" {
		t.Fatalf("unexpected paths: %q", paths)
	}
	for _, file := range files {
		if file.Language != "javascript" {
			t.Fatalf("unexpected file: %+v", file)
		}
	}
}

func TestDiscoverExcludesIDECacheAndMinifiedArtifacts(t *testing.T) {
	root := t.TempDir()
	for _, dir := range []string{".cache", ".idea", ".mypy_cache", ".next", ".nuxt", ".parcel-cache", ".pytest_cache", ".ruff_cache", ".turbo", ".vscode", "__pycache__", "build", "coverage", "dist", "node_modules", "out", "target", "vendor"} {
		writeFile(t, root, dir+"/ignored.go", "package ignored\n")
	}
	writeFile(t, root, "web/bundle.min.js", "const minified = true\n")
	writeFile(t, root, "web/bundle.min.mjs", "const minified = true\n")
	writeFile(t, root, "web/bundle.min.cjs", "const minified = true\n")
	writeFile(t, root, "web/bundle.js.map", "{}\n")
	writeFile(t, root, "web/app.js", "const app = true\n")

	files, err := Discover(context.Background(), root)
	if err != nil {
		t.Fatal(err)
	}
	if paths := filePaths(files); len(paths) != 1 || paths[0] != "web/app.js" {
		t.Fatalf("unexpected paths: %q", paths)
	}
}

func TestDiscoverHonorsMaxFileBytesBoundary(t *testing.T) {
	root := t.TempDir()
	writeFile(t, root, "at-limit.go", "0123456789")
	writeFile(t, root, "over-limit.go", "01234567890")

	files, err := DiscoverWithIndex(context.Background(), root, config.Index{MaxFileBytes: 10})
	if err != nil {
		t.Fatal(err)
	}
	if paths := filePaths(files); len(paths) != 1 || paths[0] != "at-limit.go" {
		t.Fatalf("unexpected paths: %q", paths)
	}
}
